name: 'Docker Welcome Action'
description: 'Displays a welcome message to the user.'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.name }}

inputs:
  name:
    description: 'Welcome'
    required: false
    default: 'Welcome!!'
