name: 'My Docker Action'
description: 'A Docker action that runs a Node.js script'
inputs:
  message:
    description: 'A message to print'
    required: true
    default: 'Hello, world!'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.message }}
