name: Docker Welcome Workflow

on: [push]

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Run Docker Welcome Action
      uses: ./.github/actions/docker-action
      with:
        name: 'Hello from Docker Action!'
