name: JavaScript Action

on:
    workflow_run:
      workflows: ["Node.js Setup and Linting"]
      types:
        - completed
permissions:
    pull-requests: read
  
jobs:
  js-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run JavaScript Action
        uses: ./.github/actions/js-action
        with:
          message: 'Hello from GitHub Actions!'
