name: JavaScript Action

on:
    workflow_run:
      workflows: ["Node.js Setup and Linting"]
      types:
        - completed
permissions:
    pull-requests: read
  
jobs:
  js-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16' 

      - name: Install dependencies
        run: npm install
        working-directory: .github/actions/js-action

      - name: Run JavaScript Action
        uses: ./.github/actions/js-action
        with:
          message: 'Hello from GitHub Actions!'
          
